### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Squitch1** [TareHimself/wallpaper-app#2]
Is there Any linux support planned ?

**Comment by TareHimself** [comment]
Since electron supports Linux there is, I just need to fix a lot of linting issues that occur when building for Linux

**Comment by Squitch1** [comment]
Have you planned to make some package like for the `AUR` or `debian` ?

**Comment by TareHimself** [comment]
For now, I just plan to continue using gh releases, should be up by the time you see this
